cache:
  paths:
    - ./socioprophet-web/client/node_modules/

stages:
  # - build
  # - test
  - docker_image
# build:
#   stage: build
#   image: node
#   script:
#     - echo "Build Application"
#     - make build_web
#     - make build_client
#     - echo "Build Successful!"

# test:
#   stage: test
#   image: node
#   script:
#     - echo "Testing Application"
#     - echo "Test Successful!"

# docker_image:
#   stage: docker_image
#   image: docker:stable

#   variables:
#     DOCKER_DRIVER: overlay
#     GCP_PROJECT_ID: socioprophet-web
#     IMAGE_NAME: sp-client

#   services:
#     - docker:dind

#   script:
#     - docker login -u _json_key -p "$GCLOUD_SERVICE_KEY" https://gcr.io
#     - docker pull gcr.io/socioprophet-web/sp-client:1.0.3
#     # - docker build -t "{DOCKER_IMAGE_TAG}" .
#     - docker push gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:1.0.3
#   only:
#     - master
