# image for build and test stages
image: node:latest

# cache dependecies
cache:
  paths:
    - ./socioprophet-web/client/node_modules/

stages:
  # - build
  # - test
  - docker_image

# build:
#   stage: build
#   script:
#     - make build_web
#     - make build_client

# test:
#   stage: test
#   script:
#     - "cd ./socioprophet-web/client/ && yarn test"

docker_image:
  stage: docker_image
  image: docker:stable

  variables:
    DOCKER_DRIVER: overlay
    GCP_PROJECT_ID: socioprophet-web
    IMAGE_NAME_CLIENT: sp-client
    IMAGE_NAME_SERVER: sp-server

  services:
    - docker:dind

  script:
    - echo $GCP_PROJECT_ID
    - echo $IMAGE_NAME
    - docker login -u _json_key -p "$GCLOUD_SERVICE_KEY" https://gcr.io
    #     - docker pull gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:1.0.3
    # - "cd ./socioprophet-web/client/ && docker build -t gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME_CLIENT:release-candidate ."
    # - docker push gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME_CLIENT:release-candidate
    - "cd ../server/ && docker build -t gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME_SERVER:release-candidate ."
    - docker push gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME_SERVER:release-candidate
  #   # after_script:
  #   # - docker logout  <--- add this in, not sure yet

  only:
    - master
