.PHONY: build_web run_server run_client

build_web:
	cd scripts/ && bash build_web.sh

run_server:
	cd scripts && bash run_server.sh

run_client:
	cd scripts && bash run_client.sh

build_client:
	cd scripts && bash build_client.sh