// GENERATED by scripts/generate-delivery-snapshot.mjs — do not edit by hand.
// Regenerated by CI on merge to master so the dashboard cannot drift from what shipped.
// sourceMode 'live' at commit 1ff1e6a.
import type { DeliverySnapshot } from '../features/delivery/contract';

export const deliverySnapshot: DeliverySnapshot = {
  "sourceMode": "live",
  "generatedAt": "2026-08-22T06:58:17.678Z",
  "commit": "1ff1e6ade417a672bc61347f982f370a6feeb2b8",
  "workflowRun": "https://github.com/Kyroga-AI/socioprophet/actions/runs/32558304974",
  "repo": "SocioProphet + SourceOS-Linux",
  "windowDays": 14,
  "boundaryNotice": "Estate-wide rollup across SocioProphet and SourceOS-Linux over 14 days, computed from merged-PR and issue search evidence. Boards come from registry/board-spec.yaml — Projects is a render target, not the truth. Throughput history is bucketed weekly and resampled by Monte Carlo; no velocity average is used anywhere. Cost and price inputs are DECLARED, not measured, and every money figure inherits the weakest basis of its inputs.",
  "perOrg": [
    {
      "org": "SocioProphet",
      "merged": 0,
      "openPrs": 339,
      "closedIssues": 0,
      "openIssues": 731
    },
    {
      "org": "SourceOS-Linux",
      "merged": 0,
      "openPrs": 3,
      "closedIssues": 0,
      "openIssues": 24
    }
  ],
  "history": [
    {
      "weekStart": "2026-06-13",
      "weekEnd": "2026-06-20",
      "merged": 45
    },
    {
      "weekStart": "2026-06-20",
      "weekEnd": "2026-06-27",
      "merged": 295
    },
    {
      "weekStart": "2026-06-27",
      "weekEnd": "2026-07-04",
      "merged": 370
    },
    {
      "weekStart": "2026-07-04",
      "weekEnd": "2026-07-11",
      "merged": 326
    },
    {
      "weekStart": "2026-07-11",
      "weekEnd": "2026-07-18",
      "merged": 314
    },
    {
      "weekStart": "2026-07-18",
      "weekEnd": "2026-07-25",
      "merged": 321
    },
    {
      "weekStart": "2026-07-25",
      "weekEnd": "2026-08-01",
      "merged": 432
    },
    {
      "weekStart": "2026-08-01",
      "weekEnd": "2026-08-08",
      "merged": 928
    },
    {
      "weekStart": "2026-08-08",
      "weekEnd": "2026-08-15",
      "merged": 0
    },
    {
      "weekStart": "2026-08-15",
      "weekEnd": "2026-08-22",
      "merged": 0
    }
  ],
  "arrivals": 33,
  "sprint": {
    "name": "Rolling 14-day window",
    "startedAt": "2026-08-08T06:58:17.678Z",
    "endsAt": "2026-08-22T06:58:17.678Z",
    "committed": 342,
    "completed": 0,
    "addedMidSprint": 0,
    "carriedOver": 342
  },
  "moscow": {
    "must": 0,
    "should": 0,
    "could": 0,
    "wont": 0,
    "labelsSeen": 0
  },
  "metrics": [
    {
      "id": "throughput",
      "label": "Throughput",
      "value": 0,
      "unit": "count",
      "basis": "measured",
      "better": "up",
      "evidence": "search: org:{SocioProphet|SourceOS-Linux} is:pr is:merged merged:>=2026-08-08",
      "note": "PRs merged across the estate in 14 days."
    },
    {
      "id": "throughput-median-wk",
      "label": "Median weekly throughput",
      "value": 317.5,
      "unit": "count",
      "basis": "measured",
      "better": "up",
      "evidence": "median of 10 weekly buckets",
      "note": "Median, not mean — the distribution is heavily skewed."
    },
    {
      "id": "wip",
      "label": "Work in progress",
      "value": 342,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "search: is:pr is:open across 2 orgs",
      "note": "Open pull requests across the estate."
    },
    {
      "id": "aging",
      "label": "Aging WIP",
      "value": 16,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "open PRs older than 7d",
      "note": "Open PRs older than 7 days — the flow risk."
    },
    {
      "id": "issues-closed",
      "label": "Issues closed",
      "value": 0,
      "unit": "count",
      "basis": "measured",
      "better": "up",
      "evidence": "search: is:issue is:closed closed:>=2026-08-08",
      "note": "Issues closed in 14 days."
    },
    {
      "id": "issues-open",
      "label": "Open issues",
      "value": 755,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "search: is:issue is:open",
      "note": "Open issues across the estate — the forecastable backlog."
    },
    {
      "id": "arrivals",
      "label": "Arrivals",
      "value": 33,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "search: is:pr created:>=2026-08-08",
      "note": "PRs opened in 14 days — a flow, measured so Little's Law can be validated rather than assumed."
    }
  ],
  "columns": [
    {
      "name": "Backlog (open issues)",
      "count": 755,
      "aging": 0
    },
    {
      "name": "In review (open PRs)",
      "count": 342,
      "wipLimit": 40,
      "aging": 16
    },
    {
      "name": "Merged (14d)",
      "count": 0,
      "aging": 0
    },
    {
      "name": "Closed (14d)",
      "count": 0,
      "aging": 0
    }
  ],
  "items": [
    {
      "ref": "sourceos-continuum#6",
      "title": "chore(deps): bump docker/setup-qemu-action from 3.7.0 to 4.2.0",
      "status": "In review",
      "lane": "sourceos-continuum",
      "ageDays": 48,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "sourceos-continuum#8",
      "title": "chore(deps): bump actions/checkout from 7.0.0 to 7.0.1",
      "status": "In review",
      "lane": "sourceos-continuum",
      "ageDays": 27,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "sourceos-continuum#14",
      "title": "chore(deps): bump docker/login-action from 3.7.0 to 4.6.0",
      "status": "In review",
      "lane": "sourceos-continuum",
      "ageDays": 20,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "sociosphere#636",
      "title": "repo-discovery: unregistered-repo backlog (2026-08-09)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 13,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#638",
      "title": "repo-discovery: unregistered-repo backlog (2026-08-10)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 12,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "cybernetic-genesis#19",
      "title": "ci: bump docker/setup-buildx-action from 3.12.0 to 4.2.0",
      "status": "In review",
      "lane": "cybernetic-genesis",
      "ageDays": 12,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#637",
      "title": "vendor-freshness: refresh upstream observation (2026-08-10)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 12,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "workspace-inventory#23",
      "title": "build(deps): bump actions/upload-artifact from 4.6.2 to 7.0.1",
      "status": "In review",
      "lane": "workspace-inventory",
      "ageDays": 12,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#640",
      "title": "repo-discovery: unregistered-repo backlog (2026-08-11)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 11,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#639",
      "title": "vendor-freshness: refresh upstream observation (2026-08-11)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 11,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#642",
      "title": "repo-discovery: unregistered-repo backlog (2026-08-12)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 10,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#641",
      "title": "vendor-freshness: refresh upstream observation (2026-08-12)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 10,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#644",
      "title": "repo-discovery: unregistered-repo backlog (2026-08-13)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 9,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#643",
      "title": "vendor-freshness: refresh upstream observation (2026-08-13)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 9,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#646",
      "title": "repo-discovery: unregistered-repo backlog (2026-08-14)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 8,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "sociosphere#645",
      "title": "vendor-freshness: refresh upstream observation (2026-08-14)",
      "status": "In review",
      "lane": "sociosphere",
      "ageDays": 8,
      "risk": "medium",
      "blocked": false
    }
  ],
  "gates": [
    {
      "name": "Evidence collected",
      "status": "pass",
      "detail": "Estate rollup across SocioProphet, SourceOS-Linux from live search evidence."
    },
    {
      "name": "Forecast has sufficient history",
      "status": "pass",
      "detail": "10 weekly throughput samples (minimum 6 to forecast)."
    },
    {
      "name": "Aging WIP within threshold",
      "status": "fail",
      "detail": "16 PR(s) older than 7d (threshold 10)."
    },
    {
      "name": "Board spec resolved",
      "status": "pass",
      "detail": "13 boards from /home/runner/work/socioprophet/socioprophet/.sociosphere/registry/board-spec.yaml."
    },
    {
      "name": "Backlog is prioritized (MoSCoW)",
      "status": "unverified",
      "detail": "No MoSCoW labels found on open issues — the backlog is unprioritized, so Must-share discipline cannot be assessed."
    }
  ],
  "boards": [
    "Portfolio Roadmap",
    "Spec, Ontology & Contracts",
    "Reasoning & Intelligence",
    "Governance & Control Plane",
    "SourceOS Base OS",
    "SociOS Managed Plane",
    "Model Surfaces (Labs)",
    "Agent Runtime & Terminal",
    "BearBrowser",
    "Platform & GitOps",
    "Product Surfaces",
    "Mesh & Orchestration",
    "Delivery Excellence"
  ]
} as const;
