#
# This yml file can be used to create k8 secrets in the cluster
# Use base64 encoded values: `echo -n "<username>" | base64`
#
# $ kubectl apply -f k8_secrets.yml
# $ kubectl get secrets
# (see: https://kubernetes.io/docs/concepts/configuration/secret/)
apiVersion: v1
kind: Secret
metadata:
  name:
type: Opaque
data:
  username: <user>
  password: <pass>
